export function sourceColor(source: string) {
  if (source === 'rule') return 'var(--warn)'
  if (source === 'groq') return 'var(--ok)'
  if (source === 'azure') return '#0078D4'
  return 'var(--info)'
}

export default function AiSourceBadge({ source, detailed }: { source?: string; detailed?: boolean }) {
  const s = (source || 'rule').toLowerCase()
  if (s === 'rule') {
    return (
      <span
        title="Rule-based fallback: the AI model was offline or returned no usable result, so this entry was scored by deterministic keyword/emotion rules. Treat as degraded, not low-risk."
        style={{
          background: 'color-mix(in srgb, var(--warn) 13%, transparent)', color: 'var(--warn)', fontSize: '0.6rem', padding: '2px 7px',
          borderRadius: '3px', fontWeight: 700, border: '1px solid color-mix(in srgb, var(--warn) 33%, transparent)',
        }}
      >
        {detailed ? '⚠ RULE-SCORED — MODEL OFFLINE' : '⚠ RULE'}
      </span>
    )
  }
  if (s === 'azure') {
    return (
      <span
        title="Generated by Azure AI Foundry"
        style={{
          background: 'rgba(0,120,212,0.13)', color: '#0078D4', fontSize: '0.6rem',
          padding: '2px 7px', borderRadius: '3px', fontWeight: 700, border: '1px solid rgba(0,120,212,0.35)',
        }}
      >
        ◈ AZURE
      </span>
    )
  }
  return (
    <span
      title={`Generated by ${s}`}
      style={{
        background: `${sourceColor(s)}22`, color: sourceColor(s), fontSize: '0.6rem',
        padding: '2px 7px', borderRadius: '3px', fontWeight: 600, border: `1px solid ${sourceColor(s)}44`,
      }}
    >
      {s.toUpperCase()}
    </span>
  )
}
